apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test2-sample-app-aug7 
  janus-idp.io/tekton: test2-sample-app-aug7
  backstage.io/kubernetes-id: test2-sample-app-aug7
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test2-sample-app-aug7
resources: 
- application-dev.yaml