---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test2-sample-app-aug7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test2-sample-app-aug7 
  name: test2-sample-app-aug7
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi