apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test2-sample-app-aug7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test2-sample-app-aug7 
  name: test2-sample-app-aug7
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test2-sample-app-aug7 
    weight: 100 
  wildcardPolicy: None
