apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test2-sample-app-aug7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test2-sample-app-aug7 
  name: test2-sample-app-aug7
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: test2-sample-app-aug7 
